version: '3.7'
services:
  postal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postal
    networks:
      - coolify
    environment:
      DB_HOST: '${MARIADB_CONTAINER}'
      DB_USER: '${MARIADB_USER}'
      DB_PASS: '${MARIADB_PASSWORD}'
      DB_NAME: postal
    volumes:
      - postal-data:/opt/postal/config
    ports:
      - "5000:5000"
    depends_on:
      - mariadb

networks:
  coolify:
    external: true

volumes:
  postal-data:
