version: '3.7'
services:
  postal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postal
    ports:
      - "5000:5000"  # Port for web-server; adjust if needed
    networks:
      - coolify
    environment:
      DB_HOST: '${MARIADB_CONTAINER}'
      DB_PORT: '${MARIADB_PORT}'
      DB_USER: '${MARIADB_USER}'
      DB_PASS: '${MARIADB_PASSWORD}'
      DB_NAME: postal
    volumes:
      - ./data/postal/postal.yml:/config/postal.yml  # user confif file
      - postal-data:/opt/postal/config
    command: ["postal", "web-server"]  # Ensure the correct component is specified here

networks:
  coolify:
    external: true

volumes:
  postal-data:
